import { Poppins } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Nav from '@/components/Nav';

export const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={cn('relative h-full antialiased', poppins.className)}>
        <main className="relative flex min-h-screen">
          <Nav />
          <div className="flex-grow flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
